package com.github.remynfv.emojitab

import com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo
import com.comphenix.protocol.ProtocolLibrary
import com.comphenix.protocol.ProtocolManager
import com.comphenix.protocol.wrappers.*
import com.github.remynfv.emojitab.commands.EmojiCommand
import com.github.remynfv.emojitab.utils.Configs
import com.github.remynfv.emojitab.utils.Messager
import com.github.remynfv.emojitab.utils.Permissions
import com.github.remynfv.emojitab.utils.Settings
import org.bukkit.Bukkit
import org.bukkit.configuration.InvalidConfigurationException
import org.bukkit.configuration.file.FileConfiguration
import org.bukkit.configuration.file.YamlConfiguration
import org.bukkit.entity.Player
import org.bukkit.plugin.java.JavaPlugin
import org.bukkit.scoreboard.Team
import java.io.File
import java.io.IOException
import java.util.*


private const val displayName: String = "" //Any character that is invisible

class EmojiTab : JavaPlugin()
{
    //From config.yml
    var usePermissions: Boolean = true
    var individualPermissions: Boolean = false
    var verbose: Boolean = false
    var wrappingCharacter: String = ""

    //Dim gray, courtesy of someone off mineskin.org (https://mineskin.org/14b3cfc390dc440282195d8a74b742f4)
    private var texture: String = "ewogICJ0aW1lc3RhbXAiIDogMTYyMTQxMTE5MDkyMywKICAicHJvZmlsZUlkIiA6ICJmZDQ3Y2I4YjgzNjQ0YmY3YWIyYmUxODZkYjI1ZmMwZCIsCiAgInByb2ZpbGVOYW1lIiA6ICJDVUNGTDEyIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzQ4NDYxNmVhNDI0OTk1NzI4OGE5Y2Y4ZTNhM2E0ZjVjZDU0NDYxNjk1ZTczMmM5ZWViOTA4NDBmZDRkYzg3YjQiLAogICAgICAibWV0YWRhdGEiIDogewogICAgICAgICJtb2RlbCIgOiAic2xpbSIKICAgICAgfQogICAgfQogIH0KfQ=="
    private var signature: String = "vAk/+xJkgEYANJq2FxjfX4xT5Lo+z1+YNnvWPUgLnpwgj3Vq1nqKZ24y0mHbsLROE3JCnOW1vJObFyNRBktInFXX5RhAv8yis/TSyFFhR3rjnC8ZEMSlM0gyy2K9nJxjY+jDSVBNBaBmWs1JbhPWl2zN/eaMEMivAwZmBLqhTLIV/o4IAUAIPDkxdEw5MGtp81wEot1YSMc1PkGYANx7VTGUy2eCe4AhjDgUrWLkGPkSWeCowU1xQzT5DeWw5V6sylRWXR7DTkzonteRA5jO4gXrXXt5CdytGbz8SOT9V2xnhUPbnRZOgeRKwwHphAJ4N+g2+C5BGxrfSlnmj8YZKAlM17YEK2ej1eClxmmxIW/2bjZnCJR0U7f750evnXb6ZcjIQ+P400RpSCUo79L9cbvz3rHU36IcHKl3GmGG9uyr15C6DVa5WGj5A19fmzIMyRG5e5GTH6NPVC+yK5R0M36in88iP1HQFY9CdPn9NixrdRcCcXPcOcKFsNXE6la+UMhSlsXX+FS5zGtMvTedn5fPglP0DWur9Iz4Z/Bk5ZoZ93NdpF/h63rLZG9xYBs+gf8UEESPRykZSB2wIRO4039s3TC4g8i/lUBn4Zt6IpUiXip9rK7ihKdy3bVX8YywxmCL9oqhfQK0jnFk1dPDBCs/QDMCYnP4fLkLEqPZRrI="

    //This is emojis.yml
    private lateinit var emojisConfig: FileConfiguration

    //The Great Emojifier class, where most of the work gets done
    lateinit var emojifier: Emojifier

    /**
     * The "textures" property that contains the skin information for the autogenerated emoji players.
     */
    private lateinit var defaultTexturesProperty: WrappedSignedProperty //Init in generateEmojiPackets

    /**
     * Packet to add all emojis.
     */
    private lateinit var addEmojisPacket: WrapperPlayServerPlayerInfo

    /**
     * Packet to remove all emojis.
     */
    private var removeEmojisPacket: WrapperPlayServerPlayerInfo? = null

    //Declare ProtocolManager
    private lateinit var protocolManager: ProtocolManager

    /**
     * Team with alphabetically last name to move
     * fake players to the bottom of the player list.
     */
    private lateinit var team: Team

    /*
    TODO Move player update functions into own class, declutter this class
     */
    override fun onEnable()
    {
        // Plugin startup logic
        Messager.send("Loaded!")

        //Init protocol manager
        protocolManager = ProtocolLibrary.getProtocolManager()

        Bukkit.shouldSendChatPreviews()

        team = Bukkit.getScoreboardManager().mainScoreboard.getTeam("zzzzzzzzz_emoji_tab")
            ?: Bukkit.getScoreboardManager().mainScoreboard.registerNewTeam("zzzzzzzzz_emoji_tab")

        //Save Configs
        saveDefaultConfig()

        //Initialize emoji list
        emojifier = Emojifier(this)

        //(Re)load configs for the first time
        reloadConfigs()

        //Register commands
        getCommand("emoji")!!.setExecutor(EmojiCommand(this))

        //Register events
        server.pluginManager.registerEvents(Events(this), this)

        //Load emojis for any players who are online already
        for (player in Bukkit.getOnlinePlayers())
            sendEmojiPackets(player)
    }

    private fun generateEmojiPackets()
    {
        //Create a list of players of size = emojiMap.keys.size
        addEmojisPacket = WrapperPlayServerPlayerInfo()
        addEmojisPacket.action = EnumWrappers.PlayerInfoAction.ADD_PLAYER

        val info = ArrayList<PlayerInfoData>()
        for (shortcode in emojifier.emojiMap.keys)
        {
            val shortcode2 = shortcode.take(16)
            val randomUUID = UUID.randomUUID()
            val gameProfile = WrappedGameProfile(randomUUID, shortcode2)
            defaultTexturesProperty = WrappedSignedProperty("textures", texture, signature)
            gameProfile.properties.put("textures", defaultTexturesProperty)
            info.add(PlayerInfoData(gameProfile, 0, EnumWrappers.NativeGameMode.SURVIVAL, WrappedChatComponent.fromText(displayName)))

            team.addEntry(gameProfile.name) //Sort tab list
        }
        addEmojisPacket.data = info

        //Configure an identical packet to do the reverse.
        val removeEmojisPacket = WrapperPlayServerPlayerInfo()
        removeEmojisPacket.data = addEmojisPacket.data
        removeEmojisPacket.action = EnumWrappers.PlayerInfoAction.REMOVE_PLAYER
        this.removeEmojisPacket = removeEmojisPacket
    }

    /**
     * Sends all necessary packets to player, including emojis and tab-complete fake players
     */
    fun sendEmojiPackets(player: Player)
    {
        //If player has emojis disabled don't send them the players OR the fakeplayers
        if (Settings.getEmojiDisabled(player) || !(player.hasPermission(Permissions.USE) || !usePermissions))
            return

        addEmojisPacket.sendPacket(player)
    }

    fun sendRemoveEmojiPackets(player: Player)
    {
        removeEmojisPacket?.sendPacket(player)
    }

    override fun onDisable()
    {
        // Plugin shutdown logic
        removeAllFakePlayers() //Remove autocorrect bois for all players, to avoid clogging up the tab menu if unwanted
    }

    //Removes all fake players for server/config reloads
    private fun removeAllFakePlayers()
    {
        for (player in Bukkit.getOnlinePlayers())
            sendRemoveEmojiPackets(player)
    }

    //Big mama function that reloads everything in the correct order
    fun reloadConfigs()
    {
        reloadConfig()

        //Load config.yml settings in variables
        config.getBoolean(Configs.VERBOSE_BOOT).let { verbose = it }
        config.getBoolean(Configs.USE_PERMISSIONS).let { usePermissions = it }
        config.getBoolean(Configs.INDIVIDUAL_PERMISSIONS).let { individualPermissions = it }
        config.getString(Configs.WRAPPING_CHARACTER)?.let { wrappingCharacter = it }

        //Load custom skins
        val texture = config.getString(Configs.TEXTURE)
        val signature = config.getString(Configs.SIGNATURE)
        if (!texture.isNullOrBlank() && !signature.isNullOrBlank())
        {
            this.texture = texture
            this.signature = signature
        }

        //On first run it will be null
        if (removeEmojisPacket != null)
            removeAllFakePlayers()

        //Load the config into a variable
        createEmojiListConfig()

        //Load emojis into hashmap
        emojifier.loadEmojisFromConfig()

        //Create the packet to be sent out to players
        generateEmojiPackets()
    }

    //Get the FileConfiguration for the emoji list
    fun getEmojisConfig(): FileConfiguration
    {
        return this.emojisConfig
    }

    //Load emojis.yml into emojisConfig
    private fun createEmojiListConfig()
    {
        val emojisConfigFile = File(dataFolder, "emojis.yml")

        //Create emojis.yml if it doesn't exist yet.
        if (!emojisConfigFile.exists())
        {
            emojisConfigFile.parentFile.mkdirs()
            saveResource("emojis.yml", false)
        }

        //Load 'em in and hope it doesn't break
        emojisConfig = YamlConfiguration()
        try
        {
            emojisConfig.load(emojisConfigFile)
        } catch (e: IOException)
        {
            e.printStackTrace()
        } catch (e: InvalidConfigurationException)
        {
            e.printStackTrace()
        }
    }
}